// Code generated by protoc-gen-bm v0.1, DO NOT EDIT.
// source: api.proto

package api

import (
	"context"

	bm "github.com/bilibili/kratos/pkg/net/http/blademaster"
	"github.com/bilibili/kratos/pkg/net/http/blademaster/binding"
)
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"

// to suppressed 'imported but not used warning'
var _ *bm.Context
var _ context.Context
var _ binding.StructValidator

var PathWorknetProfessionPing = "/service.v1.WorknetProfession/Ping"
var PathWorknetProfessionWorknetProfessionChoice = "/service.v1.WorknetProfession/WorknetProfessionChoice"
var PathWorknetProfessionWorknetProfessionSalary = "/service.v1.WorknetProfession/WorknetProfessionSalary"
var PathWorknetProfessionWorknetProfessionTypeNumber = "/service.v1.WorknetProfession/WorknetProfessionTypeNumber"
var PathWorknetProfessionWorknetProfessionTypeSalary = "/service.v1.WorknetProfession/WorknetProfessionTypeSalary"

var PathTokenVerify = "/service.v1.Token/Verify"

// WorknetProfessionBMServer is the server API for WorknetProfession service.
type WorknetProfessionBMServer interface {
	Ping(ctx context.Context, req *google_protobuf1.Empty) (resp *google_protobuf1.Empty, err error)

	// `method:"POST"`
	WorknetProfessionChoice(ctx context.Context, req *google_protobuf1.Empty) (resp *WorknetProfessionChoiceResp, err error)

	// `method:"POST"`
	WorknetProfessionSalary(ctx context.Context, req *google_protobuf1.Empty) (resp *WorknetProfessionSalaryResp, err error)

	// `method:"POST"`
	WorknetProfessionTypeNumber(ctx context.Context, req *google_protobuf1.Empty) (resp *WorknetProfessionChoiceResp, err error)

	// `method:"POST"`
	WorknetProfessionTypeSalary(ctx context.Context, req *google_protobuf1.Empty) (resp *WorknetProfessionSalaryResp, err error)
}

var WorknetProfessionSvc WorknetProfessionBMServer

func worknetProfessionPing(c *bm.Context) {
	p := new(google_protobuf1.Empty)
	if err := c.BindWith(p, binding.Default(c.Request.Method, c.Request.Header.Get("Content-Type"))); err != nil {
		return
	}
	resp, err := WorknetProfessionSvc.Ping(c, p)
	c.JSON(resp, err)
}

func worknetProfessionWorknetProfessionChoice(c *bm.Context) {
	p := new(google_protobuf1.Empty)
	if err := c.BindWith(p, binding.Default(c.Request.Method, c.Request.Header.Get("Content-Type"))); err != nil {
		return
	}
	resp, err := WorknetProfessionSvc.WorknetProfessionChoice(c, p)
	c.JSON(resp, err)
}

func worknetProfessionWorknetProfessionSalary(c *bm.Context) {
	p := new(google_protobuf1.Empty)
	if err := c.BindWith(p, binding.Default(c.Request.Method, c.Request.Header.Get("Content-Type"))); err != nil {
		return
	}
	resp, err := WorknetProfessionSvc.WorknetProfessionSalary(c, p)
	c.JSON(resp, err)
}

func worknetProfessionWorknetProfessionTypeNumber(c *bm.Context) {
	p := new(google_protobuf1.Empty)
	if err := c.BindWith(p, binding.Default(c.Request.Method, c.Request.Header.Get("Content-Type"))); err != nil {
		return
	}
	resp, err := WorknetProfessionSvc.WorknetProfessionTypeNumber(c, p)
	c.JSON(resp, err)
}

func worknetProfessionWorknetProfessionTypeSalary(c *bm.Context) {
	p := new(google_protobuf1.Empty)
	if err := c.BindWith(p, binding.Default(c.Request.Method, c.Request.Header.Get("Content-Type"))); err != nil {
		return
	}
	resp, err := WorknetProfessionSvc.WorknetProfessionTypeSalary(c, p)
	c.JSON(resp, err)
}

// RegisterWorknetProfessionBMServer Register the blademaster route
func RegisterWorknetProfessionBMServer(e *bm.Engine, server WorknetProfessionBMServer) {
	WorknetProfessionSvc = server
	e.GET("/service.v1.WorknetProfession/Ping", worknetProfessionPing)
	e.POST("/service.v1.WorknetProfession/WorknetProfessionChoice", worknetProfessionWorknetProfessionChoice)
	e.POST("/service.v1.WorknetProfession/WorknetProfessionSalary", worknetProfessionWorknetProfessionSalary)
	e.POST("/service.v1.WorknetProfession/WorknetProfessionTypeNumber", worknetProfessionWorknetProfessionTypeNumber)
	e.POST("/service.v1.WorknetProfession/WorknetProfessionTypeSalary", worknetProfessionWorknetProfessionTypeSalary)
}

// TokenBMServer is the server API for Token service.
type TokenBMServer interface {
	// `method:"POST" internal:"true"`
	Verify(ctx context.Context, req *VerifyTokenReq) (resp *VerifyTokenResp, err error)
}

var TokenSvc TokenBMServer

func tokenVerify(c *bm.Context) {
	p := new(VerifyTokenReq)
	if err := c.BindWith(p, binding.Default(c.Request.Method, c.Request.Header.Get("Content-Type"))); err != nil {
		return
	}
	resp, err := TokenSvc.Verify(c, p)
	c.JSON(resp, err)
}

// RegisterTokenBMServer Register the blademaster route
func RegisterTokenBMServer(e *bm.Engine, server TokenBMServer) {
	TokenSvc = server
	e.POST("/service.v1.Token/Verify", tokenVerify)
}
